import type { Recipe } from "../recipeRunner"

export const calculatorRecipe: Recipe = {
  id: "calculator",
  name: "Simple Calculator",
  description: "Build a working calculator with two number inputs, four operation buttons, and a result display. Learn how inputs, buttons, and math blocks connect.",
  difficulty: "beginner",
  estimated_steps: 10,
  objects_used: ["input", "button", "text", "container"],
  logic_used: ["math"],
  icon: "🧮",
  steps: [
    {
      step: 1,
      title: "Create the result display",
      aria_says: "Let's build a calculator! First, we need somewhere to show the answer. I'm adding a text display at the top.",
      actions: [
        { fn: "add_text", args: { text: "0", size: 28 } },
        { fn: "set_position", args: { x: 40, y: 100 } },
        { fn: "set_width", args: { width: 240 } },
        { fn: "rename_object", args: { name: "Result" } },
        { fn: "set_color", args: { color: "cyan" } },
      ],
      explain: "Every calculator needs an output display. This text object will update when math blocks process your input. We made it wide (240px) and cyan colored so it stands out.",
    },
    {
      step: 2,
      title: "Add first number input",
      aria_says: "Now I'll add an input field for the first number. You'll type your numbers here.",
      actions: [
        { fn: "add_input", args: { input_type: "number", placeholder: "Number A" } },
        { fn: "set_position", args: { x: 20, y: 180 } },
        { fn: "set_width", args: { width: 120 } },
        { fn: "rename_object", args: { name: "NumA" } },
      ],
      explain: "Input objects accept user text or numbers. We set it to 'number' type so only digits work. The placeholder 'Number A' tells the user what to enter.",
    },
    {
      step: 3,
      title: "Add second number input",
      aria_says: "And a second input for the other number. I'll place it next to the first one.",
      actions: [
        { fn: "add_input", args: { input_type: "number", placeholder: "Number B" } },
        { fn: "set_position", args: { x: 160, y: 180 } },
        { fn: "set_width", args: { width: 120 } },
        { fn: "rename_object", args: { name: "NumB" } },
      ],
      explain: "Two inputs side by side — one for each operand. Later we'll wire these to math blocks that read their values.",
    },
    {
      step: 4,
      title: "Add the Add button",
      aria_says: "Now the operation buttons. Starting with addition. This button will add the two numbers when tapped.",
      actions: [
        { fn: "add_button", args: { button_label: "+", target: "", action: "" } },
        { fn: "set_position", args: { x: 20, y: 260 } },
        { fn: "set_width", args: { width: 55 } },
        { fn: "set_height", args: { height: 44 } },
        { fn: "rename_object", args: { name: "Add" } },
        { fn: "set_color", args: { color: "green" } },
      ],
      explain: "Buttons are the triggers in our logic system. When tapped, they fire their output value through any connected wires. We'll wire this to a math block next.",
    },
    {
      step: 5,
      title: "Add the Subtract button",
      aria_says: "Now the subtract button — blue to differentiate from the green add.",
      actions: [
        { fn: "add_button", args: { button_label: "\u2212", target: "", action: "" } },
        { fn: "set_position", args: { x: 80, y: 260 } },
        { fn: "set_width", args: { width: 55 } },
        { fn: "rename_object", args: { name: "Sub" } },
        { fn: "set_color", args: { color: "blue" } },
      ],
      explain: "Each operation gets its own button and color. Color coding helps users quickly identify operations — a common UX pattern.",
    },
    {
      step: 6,
      title: "Add Multiply and Divide buttons",
      aria_says: "Two more — multiply in orange and divide in red. The full set of basic operations.",
      actions: [
        { fn: "add_button", args: { button_label: "\u00d7", target: "", action: "" } },
        { fn: "set_position", args: { x: 140, y: 260 } },
        { fn: "set_width", args: { width: 55 } },
        { fn: "rename_object", args: { name: "Mul" } },
        { fn: "set_color", args: { color: "orange" } },
        { fn: "add_button", args: { button_label: "\u00f7", target: "", action: "" } },
        { fn: "set_position", args: { x: 200, y: 260 } },
        { fn: "set_width", args: { width: 55 } },
        { fn: "rename_object", args: { name: "Div" } },
        { fn: "set_color", args: { color: "red" } },
      ],
      explain: "Four colored buttons for four operations. This completes the input interface — the user can now see exactly what they'll get.",
    },
    {
      step: 7,
      title: "Create the addition logic",
      aria_says: "Now the magic! I'm creating a math block that reads Number A and Number B, adds them, and sends the result to the display. Watch — the wiring happens behind the scenes.",
      actions: [
        { fn: "select_object", args: { label: "Add" } },
        { fn: "add_logic_block", args: { block_type: "math" } },
        { fn: "configure_math", args: { label: "Math 1", operation: "add", left_object: "NumA", left_property: "inputValue", right_object: "NumB", right_property: "inputValue" } },
        { fn: "connect_wire", args: { from_label: "Add", to_label: "Math 1" } },
        { fn: "connect_wire", args: { from_label: "Math 1", to_label: "Result", to_port: "textContent" } },
      ],
      explain: "The Math block reads NumA's value as the left operand and NumB's value as the right operand. When the Add button is tapped, it triggers the math block which computes A + B and sends the result to the display. Open the Logic Editor to see the visual graph.",
    },
    {
      step: 8,
      title: "Wire the subtract button",
      aria_says: "Same pattern for subtraction — a math block that reads both inputs but subtracts instead of adding.",
      actions: [
        { fn: "select_object", args: { label: "Sub" } },
        { fn: "add_logic_block", args: { block_type: "math" } },
        { fn: "configure_math", args: { label: "Math 2", operation: "subtract", left_object: "NumA", left_property: "inputValue", right_object: "NumB", right_property: "inputValue" } },
        { fn: "connect_wire", args: { from_label: "Sub", to_label: "Math 2" } },
        { fn: "connect_wire", args: { from_label: "Math 2", to_label: "Result", to_port: "textContent" } },
      ],
      explain: "Exact same wiring pattern — button triggers a math block that reads from both inputs. The only difference is the operation: subtract instead of add. This is the power of reusable patterns.",
    },
    {
      step: 9,
      title: "Wire multiply and divide",
      aria_says: "Two more — multiply and divide. Same pattern, different operations. After this, all four buttons work!",
      actions: [
        { fn: "select_object", args: { label: "Mul" } },
        { fn: "add_logic_block", args: { block_type: "math" } },
        { fn: "configure_math", args: { label: "Math 3", operation: "multiply", left_object: "NumA", left_property: "inputValue", right_object: "NumB", right_property: "inputValue" } },
        { fn: "connect_wire", args: { from_label: "Mul", to_label: "Math 3" } },
        { fn: "connect_wire", args: { from_label: "Math 3", to_label: "Result", to_port: "textContent" } },
        { fn: "select_object", args: { label: "Div" } },
        { fn: "add_logic_block", args: { block_type: "math" } },
        { fn: "configure_math", args: { label: "Math 4", operation: "divide", left_object: "NumA", left_property: "inputValue", right_object: "NumB", right_property: "inputValue" } },
        { fn: "connect_wire", args: { from_label: "Div", to_label: "Math 4" } },
        { fn: "connect_wire", args: { from_label: "Math 4", to_label: "Result", to_port: "textContent" } },
      ],
      explain: "All four operations follow the identical pattern: Button → Math Block (configured with operation + two input sources) → Result display. Once you see this pattern, you can build any computation by swapping the operation.",
    },
    {
      step: 10,
      title: "Your full calculator works!",
      aria_says: "All four operations are wired! Try it — type two numbers and tap any button. Plus adds, minus subtracts, times multiplies, divide divides. You just built a real calculator from scratch!",
      actions: [],
      explain: "You've built a fully functional 4-operation calculator from primitive objects and logic blocks. The key insight: every button follows the same pattern (trigger → math block → display). This composable pattern is the foundation of every app you'll build in SU Lab.",
      pause: true,
    },
  ],
}
