import type { Recipe } from "../recipeRunner"

export const catchGameRecipe: Recipe = {
  id: "catch-game",
  name: "Catch Game",
  description: "Build a game with a player you move using directional buttons. Learn movement math: buttons trigger position calculations that move objects on the canvas.",
  difficulty: "intermediate",
  estimated_steps: 10,
  objects_used: ["shape", "button", "counter", "text"],
  logic_used: ["math"],
  icon: "🎯",
  steps: [
    {
      step: 1,
      title: "Set the stage",
      aria_says: "Let's build a catch game! Dark background to make the player and target pop.",
      actions: [
        { fn: "set_background", args: { color: "dark" } },
      ],
      explain: "A dark background provides contrast for bright game objects. This is standard in game design.",
    },
    {
      step: 2,
      title: "Create the player and target",
      aria_says: "A cyan player circle and a yellow target to chase. The player starts centered, the target is placed elsewhere.",
      actions: [
        { fn: "add_object", args: { shape: "circle" } },
        { fn: "set_position", args: { x: 140, y: 200 } },
        { fn: "set_size", args: { size: 40 } },
        { fn: "set_color", args: { color: "cyan" } },
        { fn: "rename_object", args: { name: "Player" } },
        { fn: "add_object", args: { shape: "circle" } },
        { fn: "set_position", args: { x: 60, y: 100 } },
        { fn: "set_size", args: { size: 25 } },
        { fn: "set_color", args: { color: "yellow" } },
        { fn: "rename_object", args: { name: "Target" } },
      ],
      explain: "Two objects with different sizes and colors — the larger cyan player and smaller yellow target. Size difference makes it clear which one you control.",
    },
    {
      step: 3,
      title: "Add the score counter",
      aria_says: "A score counter at the top. You can tap the + button when you reach the target.",
      actions: [
        { fn: "add_counter", args: { label: "Score" } },
        { fn: "set_position", args: { x: 100, y: 30 } },
        { fn: "set_width", args: { width: 100 } },
        { fn: "rename_object", args: { name: "Score" } },
        { fn: "set_color", args: { color: "green" } },
      ],
      explain: "The score counter gives immediate feedback. For now you tap +/- manually — in a full game, a collision listener would auto-increment it.",
    },
    {
      step: 4,
      title: "Build the D-pad",
      aria_says: "Four directional buttons arranged as a D-pad. These will move the player around the canvas.",
      actions: [
        { fn: "add_button", args: { button_label: "\u25B2", target: "", action: "" } },
        { fn: "set_position", args: { x: 125, y: 340 } },
        { fn: "set_width", args: { width: 50 } },
        { fn: "set_height", args: { height: 40 } },
        { fn: "rename_object", args: { name: "Up" } },
        { fn: "set_color", args: { color: "blue" } },
        { fn: "add_button", args: { button_label: "\u25BC", target: "", action: "" } },
        { fn: "set_position", args: { x: 125, y: 425 } },
        { fn: "set_width", args: { width: 50 } },
        { fn: "set_height", args: { height: 40 } },
        { fn: "rename_object", args: { name: "Down" } },
        { fn: "set_color", args: { color: "blue" } },
        { fn: "add_button", args: { button_label: "\u25C0", target: "", action: "" } },
        { fn: "set_position", args: { x: 70, y: 382 } },
        { fn: "set_width", args: { width: 50 } },
        { fn: "set_height", args: { height: 40 } },
        { fn: "rename_object", args: { name: "Left" } },
        { fn: "set_color", args: { color: "blue" } },
        { fn: "add_button", args: { button_label: "\u25B6", target: "", action: "" } },
        { fn: "set_position", args: { x: 180, y: 382 } },
        { fn: "set_width", args: { width: 50 } },
        { fn: "set_height", args: { height: 40 } },
        { fn: "rename_object", args: { name: "Right" } },
        { fn: "set_color", args: { color: "blue" } },
      ],
      explain: "The D-pad is arranged as a cross: Up top, Down bottom, Left and Right in the middle. Each button is 50x40 — big enough to tap on mobile. The layout is universally recognized from game controllers.",
    },
    {
      step: 5,
      title: "Add movement math blocks",
      aria_says: "Four math blocks — one for each direction. Each reads the Player's current position and adds or subtracts 20 pixels.",
      actions: [
        { fn: "add_math_block", args: { label: "MoveUp", operation: "subtract", value: 20 } },
        { fn: "add_math_block", args: { label: "MoveDown", operation: "add", value: 20 } },
        { fn: "add_math_block", args: { label: "MoveLeft", operation: "subtract", value: 20 } },
        { fn: "add_math_block", args: { label: "MoveRight", operation: "add", value: 20 } },
      ],
      explain: "Each math block is a position calculator: MoveUp subtracts 20 from Y (up on screen), MoveDown adds 20 to Y, MoveLeft subtracts 20 from X, MoveRight adds 20 to X. The 20px step gives smooth but visible movement.",
    },
    {
      step: 6,
      title: "Configure math blocks to read Player position",
      aria_says: "Each math block needs to know the Player's current position. I'll configure them to read Player.x or Player.y as the left operand.",
      actions: [
        { fn: "configure_math", args: { label: "MoveUp", operation: "subtract", left_object: "Player", left_property: "y", value: 20 } },
        { fn: "configure_math", args: { label: "MoveDown", operation: "add", left_object: "Player", left_property: "y", value: 20 } },
        { fn: "configure_math", args: { label: "MoveLeft", operation: "subtract", left_object: "Player", left_property: "x", value: 20 } },
        { fn: "configure_math", args: { label: "MoveRight", operation: "add", left_object: "Player", left_property: "x", value: 20 } },
      ],
      explain: "This is the key insight: each math block reads a LIVE property from the Player object. MoveUp reads Player.y, subtracts 20, and outputs the new Y. Because it reads the current position each time, the movement accumulates — tap Up three times and the player moves 60px up.",
    },
    {
      step: 7,
      title: "Wire buttons through math to Player",
      aria_says: "Final wiring! Each button triggers its math block, and each math block writes to the Player's position.",
      actions: [
        { fn: "connect_wire", args: { from_label: "Up", to_label: "MoveUp" } },
        { fn: "connect_wire", args: { from_label: "Down", to_label: "MoveDown" } },
        { fn: "connect_wire", args: { from_label: "Left", to_label: "MoveLeft" } },
        { fn: "connect_wire", args: { from_label: "Right", to_label: "MoveRight" } },
        { fn: "connect_wire", args: { from_label: "MoveUp", to_label: "Player", to_port: "y" } },
        { fn: "connect_wire", args: { from_label: "MoveDown", to_label: "Player", to_port: "y" } },
        { fn: "connect_wire", args: { from_label: "MoveLeft", to_label: "Player", to_port: "x" } },
        { fn: "connect_wire", args: { from_label: "MoveRight", to_label: "Player", to_port: "x" } },
      ],
      explain: "The complete chain: Button tap → Math block reads current position → Computes new position → Writes to Player. The button's actual output value doesn't matter — it just triggers the chain. The math block does the real work by reading Player.x or Player.y live.",
    },
    {
      step: 8,
      title: "Add collision detection",
      aria_says: "The magic — a collision block! It checks if Player and Target overlap after every move. If they collide, the Target teleports to a random spot and your Score goes up!",
      actions: [
        { fn: "add_collision_block", args: { label: "HitCheck", object_a: "Player", object_b: "Target", threshold: 35 } },
        { fn: "connect_wire", args: { from_label: "Player", to_label: "HitCheck" } },
        { fn: "connect_wire", args: { from_label: "HitCheck", to_label: "Score", to_port: "counterValue" } },
      ],
      explain: "The collision block checks center-to-center distance between Player and Target. Threshold 35 means they need to overlap within 35px. When hit: Target repositions randomly and the collision signal (1) propagates through wires to increment the Score. The wire from Player ensures the check runs after every move.",
    },
    {
      step: 9,
      title: "Game ready — go catch!",
      aria_says: "Use the D-pad to chase the Target! When you reach it, it teleports and your score goes up. How many can you catch?",
      actions: [],
      explain: "You've built a complete game loop: input (D-pad) → state update (math blocks) → collision check → feedback (score + target reposition). This is the core of every game engine: input → update → check → render. The same pattern scales from this simple catch game to complex 2D platformers.",
      pause: true,
    },
  ],
}
