import type { Recipe } from "../recipeRunner"

export const moodTrackerRecipe: Recipe = {
  id: "mood-tracker",
  name: "Mood Tracker",
  description: "Build a therapeutic mood check-in with a slider, mood label, progress bar, and color orb. Learn math blocks and reactive data flow.",
  difficulty: "intermediate",
  estimated_steps: 10,
  objects_used: ["slider", "text", "progress", "shape"],
  logic_used: ["math", "if_else"],
  icon: "😊",
  steps: [
    {
      step: 1,
      title: "Create the mood label",
      aria_says: "Let's build a mood tracker! First, a prompt that invites you to check in.",
      actions: [
        { fn: "add_text", args: { text: "How are you feeling?", size: 18 } },
        { fn: "set_position", args: { x: 40, y: 60 } },
        { fn: "set_width", args: { width: 240 } },
        { fn: "rename_object", args: { name: "Title" } },
        { fn: "set_color", args: { color: "white" } },
      ],
      explain: "The title sets the context. In a therapeutic app, clear and gentle language matters.",
    },
    {
      step: 2,
      title: "Add the mood slider",
      aria_says: "A slider from 1 to 10. Slide to express your mood — 1 is rough, 10 is great.",
      actions: [
        { fn: "add_slider", args: { min: 1, max: 10 } },
        { fn: "set_position", args: { x: 40, y: 120 } },
        { fn: "set_width", args: { width: 200 } },
        { fn: "rename_object", args: { name: "Mood" } },
        { fn: "set_color", args: { color: "purple" } },
      ],
      explain: "Sliders are perfect for mood scales — intuitive and non-verbal. The 1-10 range is a clinical standard. Everything else in this app reacts to this one slider.",
    },
    {
      step: 3,
      title: "Add the mood word display",
      aria_says: "A text that shows how you feel in words — Rough, Okay, Good, or Great.",
      actions: [
        { fn: "add_text", args: { text: "Slide to check in", size: 22 } },
        { fn: "set_position", args: { x: 50, y: 180 } },
        { fn: "set_width", args: { width: 220 } },
        { fn: "rename_object", args: { name: "Label" } },
        { fn: "set_color", args: { color: "yellow" } },
      ],
      explain: "Translating numbers to words makes it human. '7 out of 10' is data, but 'Good' is an emotion.",
    },
    {
      step: 4,
      title: "Add a progress bar and mood orb",
      aria_says: "A progress bar that fills with your mood, and a color orb that shifts from red to green.",
      actions: [
        { fn: "add_progress", args: {} },
        { fn: "set_position", args: { x: 40, y: 250 } },
        { fn: "set_width", args: { width: 200 } },
        { fn: "rename_object", args: { name: "Bar" } },
        { fn: "set_color", args: { color: "green" } },
        { fn: "add_object", args: { shape: "circle" } },
        { fn: "set_position", args: { x: 120, y: 310 } },
        { fn: "set_size", args: { size: 60 } },
        { fn: "rename_object", args: { name: "Orb" } },
        { fn: "set_color", args: { color: "yellow" } },
      ],
      explain: "Two visual channels for the same data: the bar shows magnitude, the orb shows emotion through color. Red = distress, yellow = neutral, green = wellbeing.",
    },
    {
      step: 5,
      title: "Add math blocks for scaling",
      aria_says: "The slider sends 1-10, but the progress bar needs 0-100 and the orb needs hue 0-120. Two math blocks handle the conversion.",
      actions: [
        { fn: "add_math_block", args: { label: "x10", operation: "multiply", value: 10 } },
        { fn: "add_math_block", args: { label: "x12", operation: "multiply", value: 12 } },
      ],
      explain: "Math blocks transform values between different scales. x10 maps mood 1-10 to progress 10-100%. x12 maps mood 1-10 to hue 12-120 (red→green on the color wheel). Without these, the progress would show 5% at mood 5 and the orb would stay red.",
    },
    {
      step: 6,
      title: "Wire slider through math to targets",
      aria_says: "Wiring time! Slider feeds both math blocks. x10 drives the progress bar, x12 drives the orb color.",
      actions: [
        { fn: "connect_wire", args: { from_label: "Mood", to_label: "x10" } },
        { fn: "connect_wire", args: { from_label: "Mood", to_label: "x12" } },
        { fn: "connect_wire", args: { from_label: "x10", to_label: "Bar", to_port: "progressValue" } },
        { fn: "connect_wire", args: { from_label: "x12", to_label: "Orb", to_port: "hue" } },
      ],
      explain: "One slider drives two separate pipelines through two math blocks. This fan-out pattern is everywhere in reactive UIs — one input, multiple derived outputs. The math blocks act as adapters between different value ranges.",
    },
    {
      step: 7,
      title: "Add mood word logic",
      aria_says: "Now the mood labels! Four IF blocks map slider ranges to words: 1-3 = Rough, 4-5 = Okay, 6-7 = Good, 8-10 = Great.",
      actions: [
        { fn: "add_logic_block", args: { block_type: "if_else", label: "RoughIF" } },
        { fn: "configure_logic", args: { label: "RoughIF", operator: "<=", value: 3, then_property: "textContent", then_value: "Rough" } },
        { fn: "add_logic_block", args: { block_type: "if_else", label: "OkayIF" } },
        { fn: "configure_logic", args: { label: "OkayIF", operator: "<=", value: 5, then_property: "textContent", then_value: "Okay" } },
        { fn: "add_logic_block", args: { block_type: "if_else", label: "GoodIF" } },
        { fn: "configure_logic", args: { label: "GoodIF", operator: "<=", value: 7, then_property: "textContent", then_value: "Good" } },
        { fn: "add_logic_block", args: { block_type: "if_else", label: "GreatIF" } },
        { fn: "configure_logic", args: { label: "GreatIF", operator: "<=", value: 10, then_property: "textContent", then_value: "Great" } },
      ],
      explain: "Four IF blocks check ranges using <=. They fire in order: if mood is 2, RoughIF matches (2<=3) and sets 'Rough'. OkayIF also matches (2<=5) and overwrites with 'Okay'. Wait — that's wrong! We need the LAST match to win, so we order them from broadest to narrowest: Great fires first, Good overwrites if <=7, Okay overwrites if <=5, Rough overwrites if <=3. The final value is correct.",
    },
    {
      step: 8,
      title: "Wire mood word logic",
      aria_says: "Connecting slider to all four word blocks, and each block to the Label text. Order matters — broadest range first, narrowest last.",
      actions: [
        { fn: "connect_wire", args: { from_label: "Mood", to_label: "GreatIF" } },
        { fn: "connect_wire", args: { from_label: "Mood", to_label: "GoodIF" } },
        { fn: "connect_wire", args: { from_label: "Mood", to_label: "OkayIF" } },
        { fn: "connect_wire", args: { from_label: "Mood", to_label: "RoughIF" } },
        { fn: "connect_wire", args: { from_label: "GreatIF", to_label: "Label", to_port: "textContent" } },
        { fn: "connect_wire", args: { from_label: "GoodIF", to_label: "Label", to_port: "textContent" } },
        { fn: "connect_wire", args: { from_label: "OkayIF", to_label: "Label", to_port: "textContent" } },
        { fn: "connect_wire", args: { from_label: "RoughIF", to_label: "Label", to_port: "textContent" } },
      ],
      explain: "The wiring order is deliberate: GreatIF (<=10) fires first and always matches, setting 'Great'. Then GoodIF (<=7) overwrites with 'Good' if applicable. Then OkayIF (<=5), then RoughIF (<=3). The narrowest matching range gets the final word. This is the 'waterfall override' pattern — simple but effective.",
    },
    {
      step: 9,
      title: "Test it!",
      aria_says: "Move the slider! Watch everything react — the bar fills, the orb shifts from red to green, and the word changes. Mood 1-3: Rough. 4-5: Okay. 6-7: Good. 8-10: Great.",
      actions: [],
      explain: "You've built a complete reactive mood tracker: one slider input drives a progress bar (via ×10 math), a color orb (via ×12 math), and a mood word (via 4 IF/ELSE blocks). This fan-out pattern — one source, multiple derived views — is the foundation of every modern UI framework's reactivity system.",
      pause: true,
    },
  ],
}
