import type { Recipe } from "../recipeRunner"

export const quizRecipe: Recipe = {
  id: "quiz",
  name: "Quiz Game",
  description: "Build a quiz with questions, answer buttons, and a score counter. Learn IF/ELSE logic and how to track state with counters.",
  difficulty: "beginner",
  estimated_steps: 9,
  objects_used: ["text", "button", "counter"],
  logic_used: ["if_else", "compare"],
  icon: "❓",
  steps: [
    {
      step: 1,
      title: "Create the question display",
      aria_says: "Let's build a quiz game! First, a big text to show the question.",
      actions: [
        { fn: "add_text", args: { text: "What is 7 × 8?", size: 22 } },
        { fn: "set_position", args: { x: 30, y: 90 } },
        { fn: "set_width", args: { width: 260 } },
        { fn: "rename_object", args: { name: "Question" } },
        { fn: "set_color", args: { color: "white" } },
      ],
      explain: "The question text is the central element. In a real quiz app, this would change dynamically. For now we'll use a static question to learn the wiring pattern.",
    },
    {
      step: 2,
      title: "Add the score counter",
      aria_says: "We need a way to track the score. I'll add a counter in the top right.",
      actions: [
        { fn: "add_counter", args: { label: "Score" } },
        { fn: "set_position", args: { x: 180, y: 30 } },
        { fn: "set_width", args: { width: 100 } },
        { fn: "rename_object", args: { name: "Score" } },
        { fn: "set_color", args: { color: "green" } },
      ],
      explain: "Counters are perfect for score tracking. They have +/- buttons built in, but in our quiz we'll wire the answer buttons to increment it automatically when the answer is correct.",
    },
    {
      step: 3,
      title: "Add the correct answer button",
      aria_says: "Now the answer buttons. The correct answer is 56. I'll make it green when correct — but the user won't know which one is right!",
      actions: [
        { fn: "add_button", args: { button_label: "56", target: "", action: "" } },
        { fn: "set_position", args: { x: 30, y: 200 } },
        { fn: "set_width", args: { width: 80 } },
        { fn: "set_height", args: { height: 50 } },
        { fn: "rename_object", args: { name: "Ans1" } },
        { fn: "set_color", args: { color: "purple" } },
      ],
      explain: "This button shows '56' — the correct answer. All buttons look the same to the user (purple). The logic wiring will handle what happens when each is tapped.",
    },
    {
      step: 4,
      title: "Add first wrong answer",
      aria_says: "A wrong answer button — 48. Same purple style so the user can't tell it apart visually.",
      actions: [
        { fn: "add_button", args: { button_label: "48", target: "", action: "" } },
        { fn: "set_position", args: { x: 120, y: 200 } },
        { fn: "set_width", args: { width: 80 } },
        { fn: "set_height", args: { height: 50 } },
        { fn: "rename_object", args: { name: "Ans2" } },
        { fn: "set_color", args: { color: "purple" } },
      ],
      explain: "Wrong answers look identical to the correct one. The user must know the answer — the UI doesn't give it away. The difference is in the logic wiring.",
    },
    {
      step: 5,
      title: "Add second wrong answer",
      aria_says: "And the third option — 64. Three identical-looking buttons, only the wiring differs.",
      actions: [
        { fn: "add_button", args: { button_label: "64", target: "", action: "" } },
        { fn: "set_position", args: { x: 210, y: 200 } },
        { fn: "set_width", args: { width: 80 } },
        { fn: "set_height", args: { height: 50 } },
        { fn: "rename_object", args: { name: "Ans3" } },
        { fn: "set_color", args: { color: "purple" } },
      ],
      explain: "Three buttons that look identical. The magic is in the logic — only one is wired to increment the score. This teaches a fundamental concept: visual similarity with behavioral difference.",
    },
    {
      step: 6,
      title: "Add feedback text",
      aria_says: "We need a feedback display — it'll show 'Correct!' or 'Try again' based on which button is tapped.",
      actions: [
        { fn: "add_text", args: { text: "Tap an answer!", size: 16 } },
        { fn: "set_position", args: { x: 60, y: 290 } },
        { fn: "set_width", args: { width: 200 } },
        { fn: "rename_object", args: { name: "Feedback" } },
        { fn: "set_color", args: { color: "yellow" } },
      ],
      explain: "Feedback is crucial for learning games. This text will update dynamically when buttons are tapped — changing to green 'Correct!' or red 'Try again'.",
    },
    {
      step: 7,
      title: "Wire the correct answer",
      aria_says: "Now the logic! I'll wire button Ans1 (56, the correct answer) to increment the score and show 'Correct!'",
      actions: [
        { fn: "select_object", args: { label: "Ans1" } },
        { fn: "connect_wire", args: { from_label: "Ans1", to_label: "Score", to_port: "counterIncrement" } },
        { fn: "connect_wire", args: { from_label: "Ans1", to_label: "Feedback", to_port: "textContent" } },
      ],
      explain: "Direct wires from the correct button to both the score counter and the feedback text. When Ans1 is tapped, it sends its output value through the wires to update both targets.",
    },
    {
      step: 8,
      title: "Wire wrong answers to feedback",
      aria_says: "The wrong answer buttons should show 'Try again' but NOT change the score.",
      actions: [
        { fn: "connect_wire", args: { from_label: "Ans2", to_label: "Feedback", to_port: "textContent" } },
        { fn: "connect_wire", args: { from_label: "Ans3", to_label: "Feedback", to_port: "textContent" } },
      ],
      explain: "Wrong answers only connect to feedback, not to the score. This is the simplest form of branching — different buttons lead to different outcomes based on their wiring, not IF/ELSE logic.",
    },
    {
      step: 9,
      title: "Quiz complete!",
      aria_says: "Your quiz game works! Tap 56 and the score goes up. Tap 48 or 64 and you see the feedback. To make it more advanced, add IF/ELSE blocks to change the feedback color — green for correct, red for wrong!",
      actions: [],
      explain: "You've built the core pattern of every quiz app: question display + answer buttons + score tracking + feedback. Each additional question follows the same pattern. To make it dynamic, you could use variables to track which question you're on and listeners to detect when all questions are answered.",
      pause: true,
    },
  ],
}
