import type { Recipe } from "../recipeRunner"

export const trafficLightRecipe: Recipe = {
  id: "traffic-light",
  name: "Traffic Light",
  description: "Build a working traffic light with three colored circles and a Next button that cycles through states. Learn variables and state management.",
  difficulty: "intermediate",
  estimated_steps: 10,
  objects_used: ["shape", "button", "text", "counter"],
  logic_used: ["math", "if_else"],
  icon: "🚦",
  steps: [
    {
      step: 1,
      title: "Create the traffic light body",
      aria_says: "Let's build a traffic light! First, a dark rectangle as the housing.",
      actions: [
        { fn: "add_object", args: { shape: "square" } },
        { fn: "set_position", args: { x: 100, y: 80 } },
        { fn: "set_width", args: { width: 80 } },
        { fn: "set_height", args: { height: 220 } },
        { fn: "rename_object", args: { name: "Body" } },
        { fn: "set_color", args: { color: "black" } },
      ],
      explain: "The body is a tall dark rectangle. On a dark background, the colored lights will really pop — that's intentional contrast design.",
    },
    {
      step: 2,
      title: "Add the red light",
      aria_says: "Now the three lights. Red on top — it starts bright since traffic lights begin on red.",
      actions: [
        { fn: "add_object", args: { shape: "circle" } },
        { fn: "set_position", args: { x: 115, y: 95 } },
        { fn: "set_size", args: { size: 50 } },
        { fn: "set_color", args: { color: "red" } },
        { fn: "rename_object", args: { name: "Red" } },
      ],
      explain: "The red circle represents the stop signal. It starts fully opaque (visible) because a traffic light's initial state is typically red.",
    },
    {
      step: 3,
      title: "Add the yellow light",
      aria_says: "Yellow in the middle — starts dim since we begin on red.",
      actions: [
        { fn: "add_object", args: { shape: "circle" } },
        { fn: "set_position", args: { x: 115, y: 155 } },
        { fn: "set_size", args: { size: 50 } },
        { fn: "set_color", args: { color: "yellow" } },
        { fn: "set_opacity", args: { opacity: 0.2 } },
        { fn: "rename_object", args: { name: "Yellow" } },
      ],
      explain: "Dim lights (opacity 0.2) vs bright lights (opacity 1.0) — this is how we show which state is active visually.",
    },
    {
      step: 4,
      title: "Add the green light",
      aria_says: "Green at the bottom — also starts dim. Only red is active initially.",
      actions: [
        { fn: "add_object", args: { shape: "circle" } },
        { fn: "set_position", args: { x: 115, y: 215 } },
        { fn: "set_size", args: { size: 50 } },
        { fn: "set_color", args: { color: "green" } },
        { fn: "set_opacity", args: { opacity: 0.2 } },
        { fn: "rename_object", args: { name: "Green" } },
      ],
      explain: "Three lights, one bright, two dim. The logic system will toggle opacities based on a counter value.",
    },
    {
      step: 5,
      title: "Add the status label",
      aria_says: "A text label to show the current state — it starts as STOP.",
      actions: [
        { fn: "add_text", args: { text: "STOP", size: 18 } },
        { fn: "set_position", args: { x: 100, y: 320 } },
        { fn: "set_width", args: { width: 80 } },
        { fn: "rename_object", args: { name: "Status" } },
        { fn: "set_color", args: { color: "red" } },
      ],
      explain: "Text feedback reinforces the visual state. Colors alone shouldn't convey meaning — the text provides accessibility.",
    },
    {
      step: 6,
      title: "Add the Next button and state counter",
      aria_says: "A button to cycle states, and a counter to track which light is active. 0 = Red, 1 = Green, 2 = Yellow.",
      actions: [
        { fn: "add_button", args: { button_label: "Next", target: "", action: "" } },
        { fn: "set_position", args: { x: 90, y: 370 } },
        { fn: "set_width", args: { width: 100 } },
        { fn: "set_height", args: { height: 44 } },
        { fn: "rename_object", args: { name: "Next" } },
        { fn: "add_counter", args: { label: "State" } },
        { fn: "set_position", args: { x: 200, y: 370 } },
        { fn: "set_width", args: { width: 80 } },
        { fn: "rename_object", args: { name: "State" } },
        { fn: "set_color", args: { color: "cyan" } },
      ],
      explain: "A counter is a simple state machine! 0, 1, 2 represent our three states. The button increments it, and a math block will wrap it around using modulo.",
    },
    {
      step: 7,
      title: "Wire the button and add modulo",
      aria_says: "I'll connect the button to the counter, and add a modulo block so the state wraps: 0 → 1 → 2 → 0 → 1 → 2...",
      actions: [
        { fn: "connect_wire", args: { from_label: "Next", to_label: "State", to_port: "counterValue" } },
        { fn: "add_math_block", args: { label: "Mod3", operation: "modulo", value: 3 } },
        { fn: "connect_wire", args: { from_label: "State", to_label: "Mod3" } },
      ],
      explain: "Modulo 3 turns any counter value into 0, 1, or 2. Counter at 3 → mod 3 = 0 (back to red). Counter at 7 → mod 3 = 1 (green). This is the wrapping trick that makes state machines cycle.",
    },
    {
      step: 8,
      title: "Add logic blocks for each light",
      aria_says: "Now the brain! Three IF/ELSE blocks — each one checks if the state matches its light. If yes → bright. If no → dim.",
      actions: [
        { fn: "add_logic_block", args: { block_type: "if_else", label: "RedIF" } },
        { fn: "configure_logic", args: { label: "RedIF", operator: "==", value: 0, then_property: "opacity", then_value: 1, else_property: "opacity", else_value: 0.2 } },
        { fn: "add_logic_block", args: { block_type: "if_else", label: "GreenIF" } },
        { fn: "configure_logic", args: { label: "GreenIF", operator: "==", value: 1, then_property: "opacity", then_value: 1, else_property: "opacity", else_value: 0.2 } },
        { fn: "add_logic_block", args: { block_type: "if_else", label: "YellowIF" } },
        { fn: "configure_logic", args: { label: "YellowIF", operator: "==", value: 2, then_property: "opacity", then_value: 1, else_property: "opacity", else_value: 0.2 } },
        { fn: "add_logic_block", args: { block_type: "if_else", label: "StopIF" } },
        { fn: "configure_logic", args: { label: "StopIF", operator: "==", value: 0, then_property: "textContent", then_value: "STOP" } },
        { fn: "add_logic_block", args: { block_type: "if_else", label: "GoIF" } },
        { fn: "configure_logic", args: { label: "GoIF", operator: "==", value: 1, then_property: "textContent", then_value: "GO" } },
        { fn: "add_logic_block", args: { block_type: "if_else", label: "CautionIF" } },
        { fn: "configure_logic", args: { label: "CautionIF", operator: "==", value: 2, then_property: "textContent", then_value: "CAUTION" } },
      ],
      explain: "Six IF/ELSE blocks: three for light opacities (bright/dim) and three for the status text (STOP/GO/CAUTION). Each text block has NO else action — it only fires when its state matches, so only the correct label writes to the Status text.",
    },
    {
      step: 9,
      title: "Wire everything together",
      aria_says: "Final wiring! Mod3 feeds all three IF blocks, and each IF block controls its light's opacity.",
      actions: [
        { fn: "connect_wire", args: { from_label: "Mod3", to_label: "RedIF" } },
        { fn: "connect_wire", args: { from_label: "Mod3", to_label: "GreenIF" } },
        { fn: "connect_wire", args: { from_label: "Mod3", to_label: "YellowIF" } },
        { fn: "connect_wire", args: { from_label: "Mod3", to_label: "StopIF" } },
        { fn: "connect_wire", args: { from_label: "Mod3", to_label: "GoIF" } },
        { fn: "connect_wire", args: { from_label: "Mod3", to_label: "CautionIF" } },
        { fn: "connect_wire", args: { from_label: "RedIF", to_label: "Red", to_port: "opacity" } },
        { fn: "connect_wire", args: { from_label: "GreenIF", to_label: "Green", to_port: "opacity" } },
        { fn: "connect_wire", args: { from_label: "YellowIF", to_label: "Yellow", to_port: "opacity" } },
        { fn: "connect_wire", args: { from_label: "StopIF", to_label: "Status", to_port: "textContent" } },
        { fn: "connect_wire", args: { from_label: "GoIF", to_label: "Status", to_port: "textContent" } },
        { fn: "connect_wire", args: { from_label: "CautionIF", to_label: "Status", to_port: "textContent" } },
      ],
      explain: "The data flows: Button tap → Counter increments → Mod3 wraps to 0/1/2 → Each IF/ELSE checks its state → Sets its light bright or dim. This is a complete reactive pipeline — change one value and the whole UI updates.",
    },
    {
      step: 10,
      title: "Traffic light complete!",
      aria_says: "Tap Next and watch the lights cycle! Red → Green → Yellow → Red. Each tap advances the state. You've built a real state machine with modulo arithmetic and conditional logic!",
      actions: [],
      explain: "You've implemented one of the most important patterns in programming: a finite state machine. A single counter drives 3 conditional branches, each controlling a visual element. This same pattern powers navigation menus, multi-step forms, game levels, and traffic lights in the real world. To extend this, try adding a timer that auto-advances — replace the button with an interval listener!",
      pause: true,
    },
  ],
}
